name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      
        # GET /brands
      - name: List brands
        run: |
          postman collection run 39797948-6ffa39af-9513-47f5-8a4f-e88bae40707b \
            -e 39797948-e54b0315-cd3a-4ea2-bccd-bf1438041ea4 \
            -i "Get brands" \
            --iteration-data "./data-api-testing/get-brands.csv"

        # GET /brands/:brandId
      - name: Brand by ID
        run: |
          postman collection run 39797948-6ffa39af-9513-47f5-8a4f-e88bae40707b \
            -e 39797948-e54b0315-cd3a-4ea2-bccd-bf1438041ea4 \
            -i "Get brand by ID" \
            --iteration-data "./data-api-testing/get-brand-by-id.csv"

        # POST /brands
      - name: Create new brand
        run: |
          postman collection run 39797948-6ffa39af-9513-47f5-8a4f-e88bae40707b \
            -e 39797948-e54b0315-cd3a-4ea2-bccd-bf1438041ea4 \
            -i "Admin logs in" \
            -i "Create new brand" \
            --iteration-data "./data-api-testing/create-new-brand.csv"
